CREATE TABLE IF NOT EXISTS users (
	`uid` CHAR(11) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`verified` TINYINT(1) NOT NULL DEFAULT 0,
	`master` TINYINT(1) NOT NULL DEFAULT 0,
	`admin` TINYINT(1) NOT NULL DEFAULT 0,
	`password` VARCHAR(255) NULL,
	`date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`banned` TINYINT(1) NOT NULL DEFAULT 0,
	`delete_on` DATE NULL,
	PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
	`key` VARCHAR(255) NOT NULL,
	`description` VARCHAR(255) NULL,
	`value` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
